name: dart_json_predicate
description: An implementation of the JSON predicate proposal
version: 1.1.1
author: Andreas Reiter <andreas.reiter@iaik.tugraz.at>
homepage: https://github.com/areiter/dart-json-predicate

dependencies:
  logging: any

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
