name: dart_json_predicate
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Andreas Reiter <andreas.reiter@iaik.tugraz.at>
homepage: https://github.com/areiter/dart-json-predicate

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
